% call jorge from console:
%   octave --eval "bringONSASmFilesToONSASdocs('~/work/codigos/onsas/ONSAS.m_repo/')"

function bringONSASmFilesToONSASdocs( dirONSASm )

dirONSAS_docs = '../docs/src/' ;

addpath( genpath( '../src/' ));

fprintf( 'converting:\n' )

ONSASmFiles = {   'src/ONSAS_solve.m' ...
                ; 'examples/staticVonMisesTruss/onsasExample_staticVonMisesTruss.m' ...
                ; 'examples/uniformCurvatureCantilever/onsasExample_uniformCurvatureCantilever.m' ...
                ; 'examples/uniaxialExtension/onsasExample_uniaxialExtension.m' ...
              } ;

MDFiles    = {   'ONSAS_solve.md' ...
               ; 'staticVonMisesTruss.md' ...
               ; 'cantileverBeam.md' ...
               ; 'uniaxialExtension.md' ...
              } ;

iniLines = {  19 ...
             ; 1 ...
             ; 1 ...
             ; 1 ...
           };

for i=1:length( ONSASmFiles )
  fprintf([ '  - ' ONSASmFiles{i} '\n' ])
  m2md( [ dirONSASm ONSASmFiles{i} ] , [ dirONSAS_docs MDFiles{i} ] , 1, iniLines{i} ) ;
end
